### ISSUE TITLE
Execution behavior for rmd code chunks when knitting

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multiverse#58]
Related to #6 
Address the knitting behavior of rmd code chunks using `options` so that the entire multiverse executes, and not just the default universe.

Might need to implement tree-based optimisation at the same time to remove redundant computation.

**Comment by abhsarma** [comment]
- [ ] Highlight multiverse code chunk (as different from regular R code chunks)
- [ ] Output the results of each universe in a separate <div>

**Comment by mjskay** [comment]
I see some problems with this bit of code as written:

https://github.com/MUCollective/multiverse/blob/f0d6452dddfb5c22554f43904b1319166d37b253/R/block_exec.R#L40-L51

1. It will not support code chunks that are neither R nor multiverse code chunks. This is because (1) non-R and non-multiverse code chunks have nowhere to go in this if statement and (2) for R code chunks you are calling down to your implementation of block_exec_R instead of calling down to the non-patched version in knitr, and your implementation of block_exec_R does not support non-R code chunks (while knitr::block_exec does).

2. If knitr changes block_exec internally somehow your patch effectively undoes those changes, creating a maintenance headache.

I would suggest changing the logic to something like:

```r
if (options$engine != "multiverse") {
  # call down to whatever the original implementation of knitr::block_exec was in the loaded
  # version of the package. you will have to save that function somewhere before over-writing it
} else {
  # insert your code from above for handling multiverse code chunks
}
```

Then rename your `block_exec_R` to `block_exec_multiverse` and aim it solely at supporting the execution of multiverse code chunks. You shouldn't maintain a copy of the full implementation of `block_exec` in the multiverse package since it already exists in knitr and you can patch over and call back down to it as needed rather than copying all the code over.

**Comment by abhsarma** [comment]
I'll file a separate issue regarding your comment @mjskay but right now I can't just call down to knitr:::block_exec because we are reassigning that function in its namespace, causing an infinite recursion. Hopefully making a pull request to knitr should solve it

**Comment by mjskay** [comment]
Right, I meant copying the old version elsewhere before the hot swap so you can call down to it.

**Comment by mjskay** [comment]
"copying" in the sense of using code to create a copy, not manually copying the literal text of the function

**Comment by mjskay** [comment]
(heh)
