### ISSUE TITLE
wrapper function to access objects from within the multiverse?

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multiverse#63]
Currently if we have an object x in the multiverse which is calculated differently, to extract and operate it from all the universes, we need to do the following:

```r
multiverse_table(M) %>%
  mutate( x = map(.results, "x") ) %>%
  unnest( cols = c(x) )
```

this is kind of unintuitive, and can be made simpler by just having a wrapper function around this. Also, might be useful to format the output table from this (which would contain all the stuff including parameter assignment, and the environment object etc.)

@mjskay thoughts?

**Comment by mjskay** [comment]
Yeah the natural fit for this would have been `tidyr::hoist()` but it seems to get annoyed that `.results` is an environment and not a list. So one name for this might be something like `hoist_results` (or maybe `extract_results` or something else). A simple implementation based on `hoist` might be:

```r
hoist_results = function(.data, ..., .results = .results) {
  results_name = tidyselect::vars_pull(names(.data), {{ .results }})
  
  # convert environments to lists (needed because hoist does not like environments)
  # PS this is a terrible approach and will be slow and should be changed.
  .data[[results_name]] = lapply(.data[[results_name]], as.list)
  
  hoist(.data, {{ .results }}, ...)
}
```

Which looks like this:

```r
M = multiverse()
inside(M, {
  x_value = branch(x, .options = 1:10)
  x2 = x_value^2
})
execute_multiverse(M)

M %>%
  multiverse_table() %>%
  hoist_results("x_value", "x2")
```
```
# A tibble: 10 x 6
   .universe x     .parameter_assignment .code      x_value    x2
       <int> <chr> <list>                <list>       <int> <dbl>
 1         1 1     <named list [1]>      <list [1]>       1     1
 2         2 2     <named list [1]>      <list [1]>       2     4
 3         3 3     <named list [1]>      <list [1]>       3     9
 4         4 4     <named list [1]>      <list [1]>       4    16
 5         5 5     <named list [1]>      <list [1]>       5    25
 6         6 6     <named list [1]>      <list [1]>       6    36
 7         7 7     <named list [1]>      <list [1]>       7    49
 8         8 8     <named list [1]>      <list [1]>       8    64
 9         9 9     <named list [1]>      <list [1]>       9    81
10        10 10    <named list [1]>      <list [1]>      10   100
```

Although I dunno if you want to allow unquoted names there (it seems like maybe that would be more natural since those variables do already exist in some sense?)

**Comment by abhsarma** [comment]
Cool, I'll work on the implementation. I am kinda (not strongly) inclined to the verb `extract_vars` (or `extract_values`) rather than `extract_results` because it feels more literal.

although I feel the flow should be:

```r
M %>% extract_vars(x_value, x2)
```

instead of

```r
multiverse_table(M) %>% 
    extract_vars(x_value, x2)
```

Maybe I am missing something, but I just think the multiverse_table() can seem like an unnecessary intermediary step --- the table is supposed to provide an overview, but maybe the function should directly interact with the multiverse i.e. the multiverse_table can be used internally in the function if that makes sense?

**Comment by mjskay** [comment]
I think that makes an assumption about where in the pipeline it is, which is a little less general / imposes a little more on the user (what if someone has already extracted the multiverse table and filtered it to some subset before calling extract_vars?). I could imagine making it a generic function which could take a data frame or a multiverse object, for example.

Do you use "vars" or "variables" elsewhere? I tend to prefer not using abbreviations in APIs since everyone has autocomplete these days and it reduces ambiguity.

**Comment by abhsarma** [comment]
hmm thats a good point. Are you referring of a scenario where the user filters out some parts of the multiverse because it is not relevant for the specific task? the other scenario which I can think of where they might be filtering parts of the multiverse would be  instead of using the conditionals (i.e. filtering out incompatible branches) which would be bad practice?

And no, I don't think I use vars / variables elsewhere. We could also just call it `extract`? (although that might conflict with magrittr)

**Comment by mjskay** [comment]
> Are you referring of a scenario where the user filters out some parts of the multiverse because it is not relevant for the specific task? 

Yeah something like that. I think in good API design you *don't* want to have to design for every case, you want to design something that has the flexibility to be adapted to unanticipated cases without being a pain to learn. Allowing people to do as much as possible with existing tidyverse tools is one way to do that, so I'd design with the goal of fitting into that workflow rather than re-creating everything they need to do here unless it's needed. I think you've made a good case that the existing tidyverse tools don't quite do what's needed for variable extraction, but my guess is most everything else people would need to do are satisfied by tidyverse functions --- so we want to make sure our functions don't make those functions a pain to use.

Re names I think `extract_variables` is probably fine? It's not that long... 🤷

**Comment by abhsarma** [comment]
we could implement our own version of hoist, which lets us deal with environment. Seems like the problem is we can't call names2 on environments

**Comment by mjskay** [comment]
Hmm yeah. Could also consider opening an issue on tidyr and making a PR so that hoist could work on environments? It's not an unreasonable use case since environments are the only way to create hash tables in bash R, so it's something you could imagine other people needing to do

**Comment by abhsarma** [comment]
makes sense. should not be a separate implementation of `hoist` right? keep the same but have a if-else for x being a list or environment?

**Comment by mjskay** [comment]
Yeah. If you're gonna do a PR to tidyr my suggestion would be to open an
issue first with a reprex or two then ask if they're interested in a PR.
They might also try to fix it themselves (my guess is a desirable
implementation wouldn't be to have two different code paths with an if
statement but rather one code path that works on both lists and
environments)
