### ISSUE TITLE
Do not stop execution of multiverse if one universe throws an error

### ISSUE THREAD

**Issue by abhsarma** [MUCollective/multiverse#68]
When executing the entire multiverse, do not stop the execution if one universe encounters an error. Related to #67 .

**Comment by mjskay** [comment]
Yeah I like the idea of wrapping in a try block. I think it would be good to collect trace back objects from failed runs in a way people can inspect them, maybe have a column for that in the multiverse table?

**Comment by abhsarma** [comment]
The tryCatch thing should work and easily let return the list of errors during execution (NULL if no errors). But it only seems to work with single core linear execution (i.e. mapply or parallel::mcmapply with mc.cores = 1L). Not sure whats going on.

This suggests that `parallel` implements its own tryCatch thing, but in the following test analysis:

```r
M = multiverse()

inside(M, {
  df <- df %>%
      mutate( NextMenstrualOnset = branch(menstrual_calculation, 
        "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
        "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
        "mc_option3" ~ StartDateNext)
      ) %>%
      filter( branch(certainty,
        "cer_option1" ~ TRUE,
        "cer_option2" ~ Sure1 > 6 | (Sure2 + Sure3) > 6
      )) %>%
      mutate( test_col = "test a cat" )
})


m_tbl = attr(M, "multiverse")[['multiverse_table']]
.code_list = m_tbl[['.code']]
.env_list = m_tbl[['.results']]
.universe = seq(1:nrow(m_tbl))

results <- parallel::mcmapply(execute_code_from_universe, .code_list, .env_list)

expand(M)$.results[[3]]$df
```

It returns NULL, but replacing `parallel::mcmapply` with `mapply` returns a dataframe

```r
execute_code_from_universe <- function(.c, .env) {
  error_msg <- NULL
  tryCatch(
    invisible( lapply(.c, eval, envir = .env) ),
    error = function(e) {
      error_msg <<- e
    }
  )
  
  return(error_msg)
}
```

**Comment by mjskay** [comment]
Hmmm... Weird. Maybe try returning NULL from the error handling function after assigning e to error_msg? Dunno if parallel has weird rules for printing errors that cause things to break at that point... Only thing I can think off off the top of my head

**Comment by mjskay** [comment]
sidebar: the "mc" family does not do parallel operations on windows, so we'll want to use something else for the final version...

**Comment by mjskay** [comment]
.... so I would suggest just switching to `furrr`. Then the default will be sequential and if they've called `future::plan` it can be multicore or whatever they want.

This works as expected for me:

```r
furrr::future_map(1:5, function(x) {
  tryCatch({
      if (x == 3) {
        stop("stopping")
      } else {
        x
      }
    },
    error = function(e) {
      # whatever is returned from error becomes the
      # value returned from tryCatch() if an error
      # occurs, so you don't need to do the <<-
      # assignment thing
      e
    }
  )
})
```

```
[[1]]
NULL

[[2]]
NULL

[[3]]
<simpleError in doTryCatch(return(expr), name, parentenv, handler): stopping>

[[4]]
NULL

[[5]]
NULL
```

Still works when done on multiple cores:

```r
# *NOTE*: you would not call future::plan() inside any multiverse functions,
# the user should do that if they want parallel processing, that way the
# parallel processing setup is determined by the user (including if they
# want to do a cluster or whatever)
future::plan(future::multiprocess)
furrr::future_map(1:5, function(x) {
  tryCatch({
      if (x == 3) {
        stop("stopping")
      } else {
        NULL
      }
    },
    error = function(e) {
      e
    }
  )
})
```
```
[[1]]
NULL

[[2]]
NULL

[[3]]
<simpleError in doTryCatch(return(expr), name, parentenv, handler): stopping>

[[4]]
NULL

[[5]]
NULL
```

**Comment by abhsarma** [comment]
huh, that's strange. rstan / brms all use a version of parallel. That does work in windows right?

**Comment by abhsarma** [comment]
nvm that seems way too complicated. Should just go for furrr then

**Comment by mjskay** [comment]
also I dunno how you're communicating across processes but my guess is that you will have to pass anything you want saved through the return list, not modify the multiverse object directly on each thread/process? Otherwise multiprocess setups and setups on clusters (basically anything without shared memory) will not work.

So unless I've misunderstood something about the setup here execute_code_in_multiverse will probably have to return the modified environment the code was evaluated in.

**Comment by abhsarma** [comment]
future might have the same problem, although it allows running across `multisession`. When I run `plan(multiprocess)` I get this message
> [ONE-TIME WARNING] Forked processing ('multicore') is disabled in future (>= 1.13.0) when running R from RStudio, because it is considered unstable. Because of this, plan("multicore") will fall back to plan("sequential"), and plan("multiprocess") will fall back to plan("multisession") - not plan("multicore") as in the past. For more details, how to control forked processing or not, and how to silence this warning in future R sessions, see ?future::supportsMulticore

which suggests that this might still not allow running in parallel? You can override this in RStudio, but I'm not entirely sure if that's a better way of going about it...

It also seems that functions from external packages are not supported: https://github.com/DavisVaughan/furrr/issues/92
For me it was throwing errors `mutate() not found`, and it seems like all the packages will need to be passed into future using `future_options(packages = "magrittr")` which can get tedious if you have to do it for all the libraries?

**Comment by mjskay** [comment]
The multisession default seems fine (directly using multicore isn't cross platform compatible, so if you recommend people use multiprocess and it falls back to multisession that will still execute in parallel on every platform - unless I've misread?) 

The external package thing is an interesting problem that I suspect you'd have to solve in any framework that isn't forking (so, basically in any framework if you want it to be cross platform and/or support clusters). It sounds like future does code inspection to get a list of packages to attach, which won't work in your case because all the code in the universe to be executed is stored as unevaluated expressions. If you read the "Globals" section of [this vignette](https://cran.r-project.org/web/packages/future/vignettes/future-1-overview.html) it talks about the problem and points to the {globals} package which could offer a way to statically find necessary packages. Alternatively you could try inspecting the list of loaded namespaces and just passing that.

**Comment by abhsarma** [comment]
this discussion should really be under #54 but anyway...
is using MakeCluster and ClusterMap a bad idea? because that seems to be way faster...

**Comment by mjskay** [comment]
I guess it's a bit dissatisfying since it doesn't let the user easily control how the parallelization happens. I'm surprised it's faster though since I thought future uses parallel under the hood (and don't you still have to deal with exports with makecluster? My understanding is default workers load without external libraries loaded)

**Comment by mjskay** [comment]
In the end if it's a pain to get it working maybe the best solution is to (1) write something that works well enough for now even if it doesn't do everything we'd want and (2) write an example / something that points in the direction of how to use different parallelization approaches if people want to
