### ISSUE TITLE
Several functions won't load on multiverse version 0.5.0

### ISSUE THREAD

**Issue by greg-fauerbach** [MUCollective/multiverse#95]
Hello,

I downloaded multiverse version 0.5.0 from CRAN, and the following functions aren't loading:
1. `branch()`
2. `get_code()`
3. `parse_multiverse()`

When I attempt to call one of these functions, I get an error message, e.g:
`Error in branch() : could not find function "branch"`

I don't get this issue with other functions, like `execute_multiverse()` or `inside()`.

My system:
* I'm running macOS Mojave Version 10.14.6 on an Intel-based Mac.
* I'm using R version 4.1.1 "Kick Things"

I'd love to use this package for a project--do you have any idea what the problem might be?

Thank you,

Greg

**Comment by abhsarma** [comment]
So there are two things going on here. `parse_multiverse` and `get_code` are package internals which you should not need to use in most cases (if you absolutely must use them then you can make a call like `multiverse:::parse_multiverse` although I 'd not recommend that. So the fact that these two are not available are by design.

For `branch`, it again is not an exported function, but only treated as one when we are parsing the user declared syntax. So `branch` needs to be used within a `inside` function if you are using RScript (i.e. .R file) or inside a _multiverse code block_ if you are running the code in RMarkdown. 

Let me know if that solves the issue. If not, could you post some code snippets of what you are trying to do so that I can diagnose the problem better? Thanks!

**Comment by greg-fauerbach** [comment]
Hello,

Thank you for your quick response.

That solves the issue. I was working through the example in `readme.md`, and I copy/pasted:

`NextMenstrualOnset = branch(menstrual_calculation, 
  "mc_option1" ~ StartDateofLastPeriod + ComputedCycleLength,
  "mc_option2" ~ StartDateofLastPeriod + ReportedCycleLength,
  "mc_option3" ~ StartDateNext
)`

... and wondered why it wouldn't run properly. I didn't realize I had to call `branch` within `inside`.

Thanks,

Greg
